package SportClass;

public enum CampeonatoId {

    FUT_MUNDIAL,
    FUT_EUROCOPA,
    FUT_COPA_AMERICA,
    FUT_COPA_AFRICA,
    FUT_COPA_ORO,
    FUT_COPA_ASIATICA,
    FUT_COPA_OCEANIA,
    FUT_UEFA_NATIONS_LEAGUE,

    FUT_LALIGA,
    FUT_PREMIER_LEAGUE,
    FUT_SERIE_A,
    FUT_BUNDESLIGA,
    FUT_LIGUE_1,
    FUT_PRIMEIRA_LIGA,
    FUT_EREDIVISIE,
    FUT_MLS,

    FUT_CHAMPIONS_LEAGUE,
    FUT_EUROPA_LEAGUE,
    FUT_CONFERENCE_LEAGUE,
    FUT_COPA_DEL_REY,
    FUT_FA_CUP,
    FUT_COPPA_ITALIA,
    FUT_DFB_POKAL,
    FUT_COUPE_DE_FRANCE,
    FUT_SUPERCOPA_ESPANA,
    FUT_MUNDIAL_CLUBES,
    FUT_LIBERTADORES,
    FUT_SUDAMERICANA,

    BASK_MUNDIAL_FIBA,
    BASK_JJOO,
    BASK_EUROBASKET,
    BASK_AMERICUP,
    BASK_AFROBASKET,
    BASK_ASIA_CUP,

    BASK_NBA,
    BASK_ACB,
    BASK_EUROLEAGUE,
    BASK_EUROCUP,
    BASK_FIBA_CHAMPIONS_LEAGUE,

    BASK_COPA_DEL_REY,

    F1_MUNDIAL
}
